name: Vault
version: ${project.version}
description: "${project.description}"
authors: [cereal, Sleaker, mung3r]
website: 'https://dev.bukkit.org/projects/Vault'
api-version: 1.17

main: net.milkbowl.vault.Vault
load: startup

commands:

  vault-info:
    description: Displays information about Vault 
    usage: |
           /<command> - Displays Vault information
    permission: vault.admin

permissions:

  vault.admin:
    description: Use /vault-info
    default: op