name: ${project.name}
version: ${project.version}-b${env.TRAVIS_BUILD_NUMBER}
description: ${project.description}
authors: [cereal, Sleaker, mung3r]
website: ${project.url}
api-version: 1.13

main: ${mainClass}
load: startup

commands:

  vault-info:
    description: Displays information about Vault 
    usage: |
           /<command> - Displays Vault information
    permission: vault.admin

permissions:

  vault.admin:
    description: Use /vault-info
    default: op